### ISSUE TITLE
Spice of Life Carrot Edition not working

### ISSUE THREAD

**Issue by romaust** [Adneths/hunger-reworked#2]
Spice of Life Carrot Edition not working with this mod. It looks like the event we're using to get notified of foods being eaten:
[Spice-of-Life-Carrot-Edition/src/main/java/com/cazsius/solcarrot/tracking/FoodTracker.java](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/blob/30e76bd0ec3b7db3753cc6455022514e1ff79a35/src/main/java/com/cazsius/solcarrot/tracking/FoodTracker.java#L25)

Line 25 in [30e76bd](https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/commit/30e76bd0ec3b7db3753cc6455022514e1ff79a35)

 public static void onFoodEaten(LivingEntityUseItemEvent.Finish event) { 

is being [canceled](https://github.com/Adneths/hunger-reworked/blob/a9f2c50c7e8e554174d4ae00080d8bdfedf4ffc3/src/main/java/me/adneths/hunger_reworked/event/FoodEventHandler.java#L161) by this mod.

**Comment by Adneths** [comment]
Fixed in 6147a22842ef2c64a6d1df17ab3d4ffdbfea10fb
