### ISSUE TITLE
The stomach bar conflicts with the oxygen bar.

### ISSUE THREAD

**Issue by wumengzhixing** [Adneths/hunger-reworked#5]
Have you considered other ways to express the stomach bar?
![1](https://user-images.githubusercontent.com/88496786/214499818-80db28be-9a81-4ebf-95cf-178ca5ce9012.png)

**Comment by Adneths** [comment]
It's supposed to adapt to the height of the UI, I'll check out the issue. What version of the mod are you using?

**Comment by Adneths** [comment]
In my test environment the stomach bar pushes the air bar up, what mods are you using?

**Comment by wumengzhixing** [comment]
> In my test environment the stomach bar pushes the air bar up, what mods are you using?

The version I used was Hungerrework-1.18.2-1.1.1. Thirsty bar is Tough As Nails. In the middle is Cold Sweat. My forge is 40.2.0

**Comment by Adneths** [comment]
Using Tough As Nails, Cold Sweat, and Appleskin, the air meter renders above the thirst meter. It might be another mod that conflicts with the air meter.

**Comment by wumengzhixing** [comment]
> Using Tough As Nails, Cold Sweat, and Appleskin, the air meter renders above the thirst meter. It might be another mod that conflicts with the air meter.

Come to think of it, it's Miner's Lung mod(https://www.curseforge.com/minecraft/mc-mods/miners-lung)

**Comment by Adneths** [comment]
That also doesn't seem to be the problem, just sent the whole list

**Comment by wumengzhixing** [comment]
My friend, I found this conflicting mod. It's the levelhearts（ https://www.curseforge.com/minecraft/mc-mods/levelhearts/ ） mod. By the way, this bar is a bit long. Have you considered shortening it or using numbers?
![1](https://user-images.githubusercontent.com/88496786/216338758-49f9e28d-c8be-4536-9c2a-d491eeba2887.png)

**Comment by wumengzhixing** [comment]
Oh my friend, I found that your mod does not support the diet （ https://www.curseforge.com/minecraft/mc-mods/diet ） mod (eating food does not increase nutritional value), would you consider compatibility?
This mod is great, hope you keep up the good work

**Comment by Adneths** [comment]
Since having more than 2 bars is not sustainable in normal game play so I had not considered compressing the meter. I do plan to make it work with the Diet mod.

**Comment by wumengzhixing** [comment]
> Since having more than 2 bars is not sustainable in normal game play so I had not considered compressing the meter. I do plan to make it work with the Diet mod.

Thank you for your reply

**Comment by Adneths** [comment]
I checked out the code for LevelHearts and it seems the issue is on their side. Specifically their `IngameGui.java` does not use `ForgeIngameGui::left_height` and `ForgeIngameGui::right_height` to determine the height to draw hud elements. There is already an open issue regarding it [here](https://gitlab.com/FireController1847/levelhearts/-/merge_requests/3).
