### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by wumengzhixing** [Adneths/hunger-reworked#6]
1. I find that when used with diet, I will completely lose all the nutritional value after overstuffed. Could you please modify it to let me define or fix a figure? This would result in an overstuffed punishment worse than the death penalty
2. Make the strong_stomach effect more effective, such as boosting digestion or increasing the stomach bar by a large amount instead of just a little
These are some of my ideas when I play mod, I hope you can consider it, thank you very much for making this mod

**Comment by Adneths** [comment]
The amount of nutritional value lost increases with the level of overstuffed, at level 1 it should leave you with half. I think the strong_stomach effect boosting digestion is a good idea.

I did bug testing but not much balance testing so feedback for that is always welcome. I may just create a config so players can balance it themselves, though I'm not sure when I'll get to updating this mod.
